### ISSUE TITLE
How to build the image with larger disk

### ISSUE THREAD

**Issue by vlcinsky** [lifeeth/openwrt-in-vagrant#3]
Default size is around 52 MB.

With my development I need more (using a lot of temporary stuff), in our production system we have 1 GB.

Is there some simple method to build the virtual machine with larger disk?

**Comment by lifeeth** [comment]
closed by #4

**Comment by vlcinsky** [comment]
Hi @lifeeth 
I do not think, my pull request (which calculates the image size automatically) resolves this issue.

Anyway. Your script is really helpful to get an OpenWRT image running, but I think that enlarging the disk space is out of scope and must be resolved alternatively.

There are two options:
- the image (downloaded from somewhere) shall be built already with larger disk space
- enlarge the image manually

For me, the manual solution worked as follows:

Concept:
- set up normal openwrt instance (Vagrant or pure VirtualBox)
- within VirtualBox find the storage device file (box-1.vmdk)
- convert vmdk to raw
- append zeros to final size
- mount raw image using loopback device
- repartition, fill the filesystem ...
- convert raw image back to vmdk
- in VirtualBox unmount the existing image and mount the enlarged one (or replace the original image file with larger one). See VirtualBox instance: Settings/Storage/... 

Instructions:
- [Set up Open-Wrt in Vagrant](https://github.com/lifeeth/openwrt-in-vagrant)
- [Converting RAW <-> VDI/VMDK images](https://blog.sleeplessbeastie.eu/2012/04/29/virtualbox-convert-raw-image-to-vdi-and-otherwise/)
- [Expanding x86 OpenWrt Root partition](https://macbruins.com/2011/11/15/expanding-x86-openwrt-root-partition/)

I am fine with keeping this issue closed.

**Comment by lifeeth** [comment]
@vlcinsky Sorry for the extreme delay in responding to this. Looks like the method you mentioned is the best way of doing this with the dynamic size commit pulled in. With a static size as before all you need to do is to expand the root partition. Thanks again!
